### ISSUE TITLE
ShardingCaculatorTest测试不通过

### ISSUE THREAD

**Issue by mnisummer** [baihui212/tsharding#11]
ShardingCaculatorTest这个类测试不通过，是代码修改了，测试这部分没修改？

**Comment by FatGhosta** [comment]
应该是修改了。这个类主要算key映射到那个表的，最后那个数字对了就可以了。

**Comment by threezhang** [comment]
测试用例先看 TShardingTest 这个

ShardingCaculatorTest 因为README中给的数据不全，等我补全吧

**Comment by baihui212** [comment]
The key was mentioned by threezhang.
