### ISSUE TITLE
批量查询增加结果集合并逻辑

### ISSUE THREAD

**Issue by inotgaoshou** [baihui212/tsharding#12]
请问readme文档中说批量查询增加结果集合并逻辑，对应的代码在哪？没找到，谢谢！

**Comment by threezhang** [comment]
`Map<Integer, List<Long>> tableNoAndShopOrderIdsMap = ShardingCaculator.getTableNoAndOrderIdsMap(orderIds);
`

跨表批量查询先把ID调用这个方法，根据订单ID计算在同一个表的放到同一个集合
，业务代码要增加逻辑处理。

**Comment by LinWater** [comment]
我觉得是没有结果集合合并逻辑。 
com.mogujie.trade.tsharding.route.orm.base.TShardingRoutingInvokeFactory
 ShardingMetadata shardingMetadata = getShardingKey(method, invocation.getArgs());

**Comment by LinWater** [comment]
@threezhang 多谢

**Comment by baihui212** [comment]
The key was mentioned by threezhang.
