### ISSUE TITLE
由于此Tsharing的分库分表是针对交易订单表的Sharding需求设计的和代码有好多地方对交易订单表写死

### ISSUE THREAD

**Issue by xujin1009** [baihui212/tsharding#13]
由于此Tsharing的分库分表是针对交易订单表的Sharding需求设计的和代码有好多地方对交易订单表写死,是不是要求使用关系数据库的开发系统必须根据自身关联表的分库分表需求进行改造Tsharing吗？

**Comment by baihui212** [comment]
@xujin1009 这个可以自己扩展为可配置的。可以拿具体问题来讨论，谢谢！

**Comment by baihui212** [comment]
如上。
