### ISSUE TITLE
请教两个问题

### ISSUE THREAD

**Issue by zjg23** [baihui212/tsharding#15]
1、结果集合并的实现逻辑具体在哪个类中？
2、tsharding实现时对扩容场景是怎么考虑的？表记录是需要行级别的重新计算迁移么？

**Comment by flynoah** [comment]
1. 目前结果集合并在使用时完成，未加入到框架中，按照库号 - shardingKey group的方式进行，可以集成到框架内

	
	// 结果集
	List<XdShopOrder> result = new ArrayList<>();
	// 库号 - 分库分表主键 map
	Map<Integer, List<Long>> tableNoAndShopOrderIdsMap = ShardingCaculator.getTableNoAndOrderIdsMap(shopOrderIds);
	// 分库查询结果集合并
	for (Integer tableNo : tableNoAndShopOrderIdsMap.keySet()) {
	    result.addAll(xdShopOrderMapper.getCoreOrderByShopOrderIds(tableNoAndShopOrderIdsMap.get(tableNo)));
	}

2. 对于schema级扩容，增加DB后可以调整sharding规则，完成扩容；
对于表级扩容，组件是先计算表号再计算库号，可以方便扩容，数据迁移可以采取DB复制后再去掉冗余表的方式，调整库号取余逻辑即可；推荐初始建表时按照2的整数次幂设计大小，扩容时有一半在原有DB中

**Comment by baihui212** [comment]
谢谢反馈
