### ISSUE TITLE
Mapper注解含义

### ISSUE THREAD

**Issue by norbour** [baihui212/tsharding#9]
ShardingOrderPara/ShardingBuyerPara/ShardingSellerPara 这三个注解含义是什么？分别在什么情况下使用呢？

**Comment by FatGhosta** [comment]
这个应该蘑菇街交易系统自己根据业务定义的，不具有普适性。
具体可以看一下TShardingRoutingInvokeFactory.getShardingKey()这个方法。

**Comment by threezhang** [comment]
1. 买卖家分表规则不一样
2. Mapper的参数不一样

需要去告诉程序 用哪一个参数去进行分库分表路由

具体可以看一下这里的代码逻辑
com/mogujie/trade/tsharding/route/orm/base/TShardingRoutingInvokeFactory.java:60
com.mogujie.trade.tsharding.route.orm.base.TShardingRoutingInvokeFactory#getShardingKey

用法可以看看这儿
com.mogujie.service.tsharding.mapper.ShopOrderMapper

**Comment by baihui212** [comment]
The key was mentioned by threezhang.
